# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: dependencies-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --dev
      - run:
          name: Lint application
          command: yarn lint
      - run:
          name: Build application
          command: yarn build
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - ./

  test:
    docker:
      - image: circleci/node:8.10.0-stretch-browsers
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          environment:
            NODE_ENV: test
          command: yarn cov
      - run:
          name: Submit coverage reports to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
